#Settings for the application

# Whether to encrypt private keys
private_key_encryption: true

# Number of threads to use for processing wallets
threads: 1

#BY DEFAULT: [0,0] - all wallets
#Example: [2, 6] will run wallets 2,3,4,5,6
#[4,4] will run only wallet 4
range_wallets_to_run: [0,0]

# Whether to shuffle the list of wallets before processing
shuffle_wallets: true

# Working only if range_wallet_to_run = [0,0] 
# BY DEFAULT: [] - all wallets 
# Example: [1, 3, 8] - will run only 1, 3 and 8 wallets
exact_wallets_to_run: []

# Show wallet address in logs
show_wallet_address_logs: false

#Check for github updates
check_git_updates: true

# the log level for the application. Options: DEBUG, INFO, WARNING, ERROR
log_level : INFO

# Delay before running the new cicle of wallets after it has completed all actions (12 - 24 hrs default)
random_pause_wallet_after_completion:
  min: 43200
  max: 86400

# Random pause between actions in seconds
random_pause_between_actions:
  min: 60
  max: 180

# Random pause to start wallet in seconds
random_pause_start_wallet:
  min: 0
  max: 60

#OKX api keys
okx_api_key: ''
okx_api_secret: ''
okx_passphrase: ''

# Withdrawal amount in SOL from okx
withdrawal_amount:
  min: 0.8
  max: 1

# Keeping SOL amount in the wallet for transaction fees after witdrawal from okx
sol_balance_for_commissions:
  min: 0.05
  max: 0.08

# Minimum SOL to keep in the wallet and when to refill it by swapping from stables for network fees. See refill_usd_amount
minimal_sol_balance: 0.005

# Refill SOL for transaction fees in usd
refill_usd_amount:
  min: 8
  max: 10

# Percentage of stablecoins to swap between each swap on SPOT
stablecoin_swap_percentage:
  min: 80
  max: 100

# Swaps count per cycle on SPOT
swaps_count:
  min: 5
  max: 10

# Exclude wallets to reg on refferals coded
exclude_wallets_to_reg_ref: []

# Referral codes. Example [phoenix, anotherone] - You need to set-up your username on titan
invite_codes: []